[package]
name = "discord-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = { version = "0.11", features = ["framework"] }
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"

